### ISSUE TITLE
Prioritize Ore Type?

### ISSUE THREAD

**Issue by h355t0ph3r** [Viir/bots#11]
I don't know much about building these, wondering if there would be a way to have the bot reference a file where it searches the belt list for a specific ore.  For instance, if I want to mine Veldspar because it is most profitable in my system, I could preference that over other ores.  If present in the belt the bot takes my mining ship to, then it will approach it and mine.  If not, then it does to the second type I list, or whatever is nearest if nothing else listed.

**Comment by Viir** [comment]
What about using the entries in the overview window to filter the asteroids? Where does your bot interact the first time with an asteroid?

**Comment by h355t0ph3r** [comment]
Oh, didn't think about that. I can just drop unwanted ore from the overview.
