### ISSUE TITLE
Licence type?

### ISSUE THREAD

**Issue by michaeljones** [Viir/bots#16]
I'm curious what the licence is for this code? I would like to use the Elm BMP decoder in a commercial project but I'm not sure of how you are licensing it. I understand if you would rather keep it non-commercial.

I cannot see a licence file or reference in the project but maybe I've missed it?

**Comment by Viir** [comment]
Thank you Michael for the reminder. I added a license file now.

**Comment by michaeljones** [comment]
Thank you. Kind of you to use such a permissive licence.
