### ISSUE TITLE
Suggestion: Gherkin Scripting

### ISSUE THREAD

**Issue by devspacenine** [Viir/bots#20]
It would be awesome if these bots (especially the Eve ones) could be scripted with a [gherkin-like](https://cucumber.io/docs/gherkin/reference/) language. Just provide a file path as an argument and the bot makes decisions based off the supplied gherkin statements.

**Comment by Viir** [comment]
How would that look in practice? Where can we see an example?

**Comment by Viir** [comment]
Closing this now to reflect inactivity. When you somebody becomes interested in this again we can reopen.
