### ISSUE TITLE
Select Active Ship Not Ore Hold

### ISSUE THREAD

**Issue by yushchyr** [Viir/bots#21]
I want to make an addition to this code
 Just toggleBtn ->
                                                    endDecisionPath
                                                        (actWithoutFurtherReadings
                                                            ( "Click the toggle button to expand."
                                                            , toggleBtn |> clickOnUIElement MouseButtonLeft
                                                            )
I want it to check if there was an ore hold or not. if can not see the ore hold then switch to a regular active ship inventory.
I use Megthron and it goes into a wild chase without a cargo hold.
I'm using 2020-08-24-botengine-console and {- EVE Online mining bot version 2020-08-27.
Yes, you are outdated guys.

**Comment by Viir** [comment]
Closing this since no question remains.
Feel free to open an issue if you have any question.
