### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lisandro-iraguen** [Viir/bots#25]
I have compiled the BotEngineApp.elm with elm.exe, but I can't run it, do I need the botengine.exe to run this?

**Comment by Viir** [comment]
The easier way to run an app is to use the botengine.exe. For example, you can use the `botengine  run` command on your app file or directory path: https://github.com/Viir/bots/blob/afc83b55195cd4aa0be3dd24cb375433b249c609/guide/how-to-run-a-botengine-app.md

But you don't need to use botengine.exe. You can also reuse the infrastructure from the elm-fullstack project to run an app. Elm-fullstack already implements the volatile host.

**Comment by lisandro-iraguen** [comment]
thanks for your response!
