### ISSUE TITLE
Ban rate on Tribal Wars 2 farming bot?

### ISSUE THREAD

**Issue by Lamm-a** [Viir/bots#28]
Do you know how often people get banned using the Bot?

secondly can I have this running on my PC but still use a tablet to interact with the recruitment queue and such?

Cheers
lamma

**Comment by Viir** [comment]
> Do you know how often people get banned using the Bot?

No, maybe someone got banned.

> can I have this running on my PC but still use a tablet to interact with the recruitment queue and such?

Yes, you can. The example project for Tribal Wars 2 uses web browser specific methods to send input to the game. These methods do not require input focus on the web browser window. You can also use the same PC to do other things on the same account, using another web browser window.
