### ISSUE TITLE
Question: Mining Bot

### ISSUE THREAD

**Issue by Culain** [Viir/bots#29]
Hi,

you can set a default station where you want to unload your Ore. Is it possible to also set a Destination where you want to mine from?

Edit: Also what about a priority list for Ores to Mine?

**Comment by Viir** [comment]
> Is it possible to also set a Destination where you want to mine from?

Yes, for example, you could use an app-setting to identify a bookmark to use to travel to the mining site.
That approach would require you to create a bookmark in the game client. Does this work for you?
