### ISSUE TITLE
Slow warp to 0

### ISSUE THREAD

**Issue by 4031789** [Viir/bots#3]
Hi Michael, 

Ive tried your warp to 0 bot but am finding that autopilot is faster (up to 1 minute depending) do you think this is issues on my end?

Im new to all of this and your bot is the first that I have tried.

Thanks in advance

**Comment by 4031789** [comment]
basically what is happening each time I warp to a system, it will open the a panel where you can see warp to jump gate but will sit idle for up to 1 - 2 minutes before warping.

Thanks again

**Comment by Viir** [comment]
> basically what is happening each time I warp to a system, it will open the a panel where you can see warp to jump gate but will sit idle for up to 1 - 2 minutes before warping.

This observation reads like you are using another bot I don't know. The bot I know works different, it sends mouse clicks and uses the context menu.
You can try the warp to 0 bot at https://github.com/Viir/bots/blob/master/guide/eve-online/how-to-automate-traveling-in-eve-online-using-a-warp-to-0-autopilot.md

**Comment by blatancy** [comment]
Auto pilot is slower (and I using the right bit) than manually warping and
jumping. It uses more clicks and there is a delay.  But not more than 15-20
seconds per gate.  If you want to travel set destination then go do
something.  Come back when it gets there.   Yes it's slower.  But it's
awesome for 20+ jumps while I play a couple of cod games

**Comment by 4031789** [comment]
D:/BotEngine.exe  run-bot  --bot-source="https://github.com/Viir/bots/tree/594e01b5a1be5dd8f03b0a4a3e3360e383b2543a/implement/applications/eve-online/eve-online-warp-to-0-autopilot"

Is the one im using my pc is from 2012 and is old. Maybe it is just struggling.

**Comment by 4031789** [comment]
Now its not working at all, I don't know what the issue is, I've attached screenshots of the destination of the botengine followed by the command prompts used. Also when I try to open the botengine.exe it closes down as soon as the black screen appears. 

![Destination](https://user-images.githubusercontent.com/59923158/72498185-54e9de80-387a-11ea-85ab-2d56d2bc3bd0.PNG)

![Command Prompt](https://user-images.githubusercontent.com/59923158/72498190-5915fc00-387a-11ea-8095-b58bb2600a06.PNG)

**Comment by blatancy** [comment]
It's trying to run on that C: path.  You have it on D

**Comment by Viir** [comment]
> D:/BotEngine.exe run-bot --bot-source="https://github.com/Viir/bots/tree/594e01b5a1be5dd8f03b0a4a3e3360e383b2543a/implement/applications/eve-online/eve-online-warp-to-0-autopilot"
> 
> Is the one im using my pc is from 2012 and is old. Maybe it is just struggling.

Thank you for the clarification; I will take a closer look at timings. There may be some component taking to long on older CPUs since I would not have noticed that so far — Will post here when I know more.

**Comment by Viir** [comment]
> Now its not working at all, I don't know what the issue is, I've attached screenshots of the destination of the botengine followed by the command prompts used.

Thank you for posting the error message. It looks like we found a bug here.

To avoid this problem, I created this other version of the BotEngine console application:
https://botengine.blob.core.windows.net/blob-library/by-name/2020-01-07.BotEngine.Console.debug.zip

That zip-archive contains more files, but also a `BotEngine.exe` that you can use the same way as the other one before.

(People working on .NET Core tooling have confirmed they noticed the problem and are working on a fix. It seems like Microsoft will publish a fix in a few months, which will allow us to use the single-file publishing method again.)
Sources:

+ https://github.com/dotnet/core/issues/3830
+ https://github.com/dotnet/core-setup/issues/8314

**Comment by Viir** [comment]
@4031789 I implemented an optimization to make it much faster.

How does it look like when you run version: https://github.com/Viir/bots/tree/c383343bb44ef55a7817a6b10efdb13b124fc5a1/implement/applications/eve-online/eve-online-warp-to-0-autopilot ?

What text do you have in the console after the bot completed the first jump?

**Comment by 4031789** [comment]
Hi Michael,


The new file works a charm thank you so much for your help. If you figure out how to speed the process up on old pcs like mine feel free to let me know! Thanks again.

**Comment by Viir** [comment]
> If you figure out how to speed the process up on old pcs like mine feel free to let me know!

Yes, first step is to post the text from the console. It contains more information about how the time is spent in your case.
