### ISSUE TITLE
warp_to_0: checking modules all the time

### ISSUE THREAD

**Issue by Culain** [Viir/bots#30]
Hi,

the warp_to_0 script is checking the modules with every jump. Is it possible to disable this function (with some settings parameter), or to save the result from the first check, or at least speed it up so it doesn't block the mouse forever when checking?

Tanks

**Comment by Viir** [comment]
Sure, saving the result should be doable.
When we have a recording of such a session, I can look at it. I would look into what information you have in your modules' readings that would allow us to remember the info after the jump.

To share your session recording, you can attach the session archive directly here in the GitHub issue.
