### ISSUE TITLE
15 min max

### ISSUE THREAD

**Issue by solomoncyj** [Viir/bots#32]
i want the offline time to be longer, please

**Comment by Viir** [comment]
Why?
There is the option to use an online session and online sessions do not have this time limit. Do you see a problem with using online sessions?

**Comment by Viir** [comment]
Is this related to this repository?

**Comment by zoom-maestro** [comment]
It sounds like they are unhappy with the unpaid, "offline-session" version of BotEngine and the 15 minute runtime limit.
