### ISSUE TITLE
Problem adding settings, works fine if I dont

### ISSUE THREAD

**Issue by altaheer** [Viir/bots#42]
I added the setting of not hiding when Neutral. But it wont work, this comes up:
(ive tried other settings like unloading on a specific station, doesnt work either)

Unrecognized option '--bot-settings=hide-when-neutral-in-local = no'

**Comment by Viir** [comment]
That looks like you are using an older version of the botlab client. In this case, the solution is to install version 2021-08-23 on your system.
You can find it here: https://to.botlab.org/guide/how-to-install-the-botlab-client-and-register-the-botlab-command
Also, the updated bot for your scenario is at https://catalog.botlab.org/e025c79ef959d848559d2d7c15e527ea39c720ab6b06763ef1ccf4c08c39f902

**Comment by Viir** [comment]
To make entering settings and bot prompts easier, we introduced this graphical user interface:

![image](https://github.com/Viir/bots/assets/19209696/7782ba2f-12f5-46f8-9244-cc49841f8248)

As soon as we enter a prompt here, the system will check if the bot understands that format and display a warning message if it does not work.
