### ISSUE TITLE
Bot.elm file missing

### ISSUE THREAD

**Issue by Scaro72** [Viir/bots#44]
I too am having this issue as another person. He seemed to have worked it out but didn't explain how.

failed with exception: System.Exception: Failed compiling the bot program code: Failed to find the file with the entry point. Seems like the 'Bot.elm' file is missing in this program code file tree.

**Comment by Viir** [comment]
There are some links to outdated program codes out there.
To solve this issue you just need to run an updated version.

You can run the new version from https://catalog.botlab.org/8881e86b0ce82d9da6b4a5f89234a6406cc0c067ca2666f4c31f0982029e25ee

(The `Bot.elm` file is included there)

I updated the guides to link to the new bot: https://to.botlab.org/guide/app/tribal-wars-2-farmbot
