### ISSUE TITLE
issue with returning to station

### ISSUE THREAD

**Issue by ITuto** [Viir/bots#47]
Hello,

First thank you so much for your work! 
I had a couple issue but finally i managed to make the bot mine, and do all stuff, join asteroid without problem.
My only issue is that he never return to station, i tried to run one time the bot from the station , without any config, it didnt worked, then i started by adding in the setting my station name, but it's dont work too 

Thank for your work man, keep it up , add a paypal for donation !

**Comment by Viir** [comment]
Thank you for the feedback. Most people use the unloading to station functionality successfully. Let me know if you want help setting up the docking to the station. The data about your situation resides on your system, so it will require sharing your scenario. Besides the standard session recording (https://to.botlab.org/guide/how-to-report-an-issue-with-a-bot-or-request-a-new-feature), most people use screen sharing via Discord to quickly complete the setup if there is a problem.

**Comment by PeterPirog** [comment]
@Viir  Very  nice bot. I have some problem with returning to the station, the bot can't chose  the station from list. My code is:

`
@echo off
@echo This is a script to run the bot found at https://catalog.botlab.org/999f03ff3e728e68fca5c065d924bb3f93bc425fcdebe042c5f5128787d1ebff
@echo.
@echo Below is the beginning of the bot description found on the catalog:
@echo.
@echo {- EVE Online mining bot version 2022-08-25
@echo.
@echo    The bot warps to an asteroid belt, mines there until the mining hold is full, and then docks at a station or structure to unload the ore. It then repeats this cycle until you st
@echo [...]
@echo.
@echo This script applies the configuration found at https://catalog.botlab.org/999f03ff3e728e68fca5c065d924bb3f93bc425fcdebe042c5f5128787d1ebff/configure-run-app/eyJvbmxpbmVTZXNzaW9uIjpmYWxzZSwiYm90U2V0dGluZ3MiOiJ1bmxvYWQtc3RhdGlvbi1uYW1lID0gU3RhdGlvbiAtIENsZWxsaW5vbiBWSSAtIE1vb24gMTEgLSBDZW50ZXIgZm9yIEFkdmFuY2VkIFN0dWRpZXMgU2Nob29sIiwicGF1c2VCb3RLZXlzIjoiIiwic2Vzc2lvbkxlbmd0aExpbWl0IjoiIiwiZGV0YWlsZWRTZXNzaW9uUmVjb3JkaW5nIjoiIn0=
@echo.

where botlab.exe >nul 2>nul
if %ErrorLevel% equ 0 (
    botlab.exe  run  --bot-settings="unload-station-name = Station - Clellinon VI - Moon 11 - Center for Advanced Studies School"  https://github.com/Viir/bots/tree/71fa90b9b26f9bd0f50526e68054e7f6ac5a829d/implement/applications/eve-online**/eve-online-mining-bot
) else (
    @echo I failed to run the bot because I did not find the 'botlab.exe' program.
    @echo.
    @echo Please see https://to.botlab.org/failed-run-did-not-find-botlab-program for a guide on how to install the 'botlab.exe' program so that I can find it.
    @start "" https://to.botlab.org/failed-run-did-not-find-botlab-program
)

pause
`

**Comment by Viir** [comment]
Hi @PeterPirog, thank you for sharing your experience.
If you add the complete recording of your session, I can check why I did not pick the station.
You can attach the recording exported from the bot right here into a comment on this GitHub issue thread.
You can also send it to me via support@botlab.org

**Comment by PeterPirog** [comment]
@Viir Thank You fot the answer.
I found the reason, now in the game the station name phrase "Moon 11" has been replaced by "M11"

**Comment by Viir** [comment]
Thank you for the update. In case you run into any other problems, let me know.
