### ISSUE TITLE
Bit cant return drones and gets stuck

### ISSUE THREAD

**Issue by Mrfalk** [Viir/bots#48]
Bot keeps trying to return drones when cargo is full with out any luck to press the Button and then it stops

**Comment by Viir** [comment]
I do not see a link to your scenario. Is this related to EVE Online?

**Comment by Mrfalk** [comment]
Oh
Sorry yes eve online. I tryed to figure out why and how but no luck.
Scenario where and how do i find that

**Comment by Viir** [comment]
I can look for you when I have your session recording. The recording is stored on the computer where you ran your bot, one recording for each botting session. The session recording is enough to describe your scenario.

You find your session in this list in the graphical user interface:

![image](https://user-images.githubusercontent.com/19209696/153746750-ea8bb4c9-236f-47c5-bc42-ee9adcaed1bb.png)

If you have never exported a recording from your computer, see the guide at https://to.botlab.org/guide/how-to-report-an-issue-with-a-bot-or-request-a-new-feature#getting-the-session-recording-archive

**Comment by Viir** [comment]
I can look for you when I have your session recording. The recording is stored on the computer where you ran your bot, one recording for each botting session. The session recording is enough to describe your scenario.

You can export the recording using this button in the graphical user interface:

![image](https://user-images.githubusercontent.com/19209696/153746842-1cde9349-d7cd-413d-9611-9d81fb3cb6f6.png)

If you have never exported a recording from your computer, see the guide at https://to.botlab.org/guide/how-to-report-an-issue-with-a-bot-or-request-a-new-feature#getting-the-session-recording-archive

**Comment by danielignacak** [comment]
'Return drones to bay' doesn't work sience 02.10 patch I think. It's not the specific code. Thought its just case (it changed) but it's not.

**Comment by Viir** [comment]
@danielignacak did you run a bot session with patch 02.10?

**Comment by Viir** [comment]
Closing this since we did not get an answer within 30 days.

@Mrfalk, @danielignacak we can reopen this when you become interested again.
