### ISSUE TITLE
stuck on an action

### ISSUE THREAD

**Issue by nathanmcr** [Viir/bots#51]
stuck on "Current activity: Waiting for completion of task 'setup-2': Setup: Search the address of the UI root in process 43684" will not change.

**Comment by Viir** [comment]
Is this related to any of the bots in this repository?

**Comment by ls400hurdles** [comment]
Whats happening is the asteroid selected gets mined out before you get to 99% The icon greys out but does not fully disappear from the console and when you right-click it nothing happens. this confuses the bot and keeps it in an endless look instead of selecting the next rock in the list to right-click and mine

**Comment by Viir** [comment]
> Whats happening is the asteroid selected gets mined out before you get to 99% The icon greys out but does not fully disappear from the console and when you right-click it nothing happens.

@ls400hurdles What do you think about adapting your bot to filter the list of overview entries before picking one to click on? You could filter out the ones which appear "greyed out". Does that solve your issue?

**Comment by Viir** [comment]
We solved this with the additional filter in `clickableAsteroidsFromOverviewWindow` added in https://github.com/Viir/bots/commit/318273217db41b8f80110ad7e8dc40be937ec7ff

```Elm
clickableAsteroidsFromOverviewWindow =
    overviewWindowEntriesRepresentingAsteroids
        >> List.filter (.uiNode >> uiNodeIsLargeEnoughForClicking)
        >> List.filter (.opacityPercent >> Maybe.map ((<=) 50) >> Maybe.withDefault True)
        >> List.sortBy (.uiNode >> .totalDisplayRegion >> .y)
```

![image](https://user-images.githubusercontent.com/19209696/235344547-857ad5f8-6bd7-4ce9-8b75-f68ffb6c2e5b.png)
