### ISSUE TITLE
Is this really worth? or maybe rmt?

### ISSUE THREAD

**Issue by HongLouWang** [Viir/bots#53]
Is this really worth? 5 euro for 150hours that is nearly 6 dollar, that means if you can sell is about 30 dollars per 5000M isk, you need to get 1000M in 150 hours, that means it's impossible, I don't know how can make 6M isk by mining. If you really need isk why not go to somewhere like play auction and spend 30 dollars?

**Comment by Viir** [comment]
It depends on your goal. If you want ISK in EVE Online, you could do, for example, Abyssal Deadspace sites. This way, you can make more than 40 million ISK per hour.
