### ISSUE TITLE
MiningBot just clicks on inventory 

### ISSUE THREAD

**Issue by kethisXD** [Viir/bots#55]
Hello. I'm trying to launch a bot. I set all the settings correctly, watched the launch video, but the bot endlessly clicks on "Mining hold" in the inventory. I will be glad if you help

{
  "botlabClientVersion": "2022-10-07",
  "botId": "999f03ff3e728e68fca5c065d924bb3f93bc425fcdebe042c5f5128787d1ebff",
  "initialBotSettingsHash": "e3b0c4",
  "sessionCustomName": "2022-10-16T23-44-31",
  "onlineSessionId": null,
  "lastBotStep": {
    "sessionAgeMilliseconds": 119278,
    "statusTextFromBot": "Session performance: times unloaded: 0, volume unloaded / m\u00B3: 0\n---\n

Current reading: mining hold filled Unknown%. Shield HP at 100%. Found 0 mining modules. I do not see the drones window.

\n\u002B I see ship UI and overview, undocking complete.

\n\u002B\u002B mining hold is not selected. Select the mining hold.

\n\u002B\u002B\u002B Click the tree entry representing the mining hold.

\n----\nEVE Online framework status:\n
Last reading from game client: 000035-116264: 0 rects containing 0 pixels\n
Last result from volatile process is: Success: {\u0022CompletedEffectSequenceOnWindow\u0022:{}}\n
Current activity: Operate bot."
  },
  "finishReason": null
}

**Comment by Viir** [comment]
Thank you for sharing your experience.
No worries, we will get this sorted.
It might be that your game client has the feature "PhotonUI" enabled, and this prevents bot 999f03ff3e from reading some of the UI elements.
What do you get when you disable PhotonUI?

![image](https://user-images.githubusercontent.com/19209696/196232346-7640cb1b-3ac9-4f74-a050-5fade035a388.png)

**Comment by Viir** [comment]
We just updated the examples for EVE Online to work with the new Photon UI.

You can run the new adapted mining bot from <https://catalog.botlab.org/a689719bb197c77a>
