### ISSUE TITLE
Configured bot crashes

### ISSUE THREAD

**Issue by sargan26** [Viir/bots#56]
If I run the bat configured here it crashes.

https://catalog.botlab.org/6960e9879bb0992a

![image](https://user-images.githubusercontent.com/62548906/196289325-18ecfa86-8490-45f6-b318-1f33eae09c2c.png)

**Comment by Viir** [comment]
Bot 6960e9879bb0992a is not compatible with newer versions of the botlab client.
There is a replacement already: Bot https://catalog.botlab.org/85fd684b37c56d67 has the same farming functionality and works with the new engine.
