### ISSUE TITLE
Destroyed Asteroid locking bot.

### ISSUE THREAD

**Issue by ByzoGaming** [Viir/bots#57]
So when running the bot in online mode. A completely mined out asteroid stays on my overview, almost like a ghost icon. the bot cannot move on from that asteroid and sits for 20 mins before it disappears from the overview. is there anyway to avoid the bot trying to select something invalid? or used? 

i'm new to coding so any help is appreciated

**Comment by Viir** [comment]
Thank you for sharing your experience!
That will be an easy fix in the bot model. Adapting the model takes only a few minutes, but we need an example to train the bot to distinguish between the relevant states of the overview entry.
When you write 'almost like a ghost icon' it sounds like there might even be a visual distinction. If you make two screenshots, one before and one after the depletion of the asteroid, and look at them side-by-side, you might find a visual difference.
The approach we take then is to retrain the bot model with these examples.
I can adapt the bot model for you if you send me the session recording exported from the BotLab client.

> i'm new to coding so any help is appreciated

If you want to learn how to do the whole adaptation yourself, I will explain the process in more detail.

**Comment by ByzoGaming** [comment]
Hi, sorry for the wait, i've been at work all week, ill post some pics tomorrow for you.
