### ISSUE TITLE
BotLab is blank no content

### ISSUE THREAD

**Issue by thouger** [Viir/bots#61]
![微信截图_20221228172629](https://user-images.githubusercontent.com/11767062/209789910-54e3ba31-1693-4707-9bfb-e9f5d520fdf2.png)

download from https://botlabs.blob.core.windows.net/blob-library/by-name/2022-12-10-botlab-client.zip

**Comment by Viir** [comment]
Thank you for sharing your experience 👍
I will look into it soon.

**Comment by Viir** [comment]
Version 2023-04-21 of the BotLab client creates a new log file for every instance of the program started in the directory `%localappdata%/botlab/local-instance`

![image](https://user-images.githubusercontent.com/19209696/233746121-d668166a-f7c4-41dd-8bfa-b79438cd1334.png)

In case you see that problem again, send me the log file created in that directory, then we can see where it went wrong.

**Comment by thouger** [comment]
i change my computer,it is no problem,thank viir,i can't show the log.sorry
