### ISSUE TITLE
Search the address of the UI root in process 548

### ISSUE THREAD

**Issue by Sergizan37** [Viir/bots#68]
Idk why all is perfect configured and dont work. 
![image](https://user-images.githubusercontent.com/73033344/218207361-e262e15d-38d0-4533-ac2f-458686836692.png)

**Comment by Viir** [comment]
Thank you for sharing your experience!
When you send me the session recording, I will look into it to find out what was causing this problem.
You can use the button labeled 'Export session recording archive' here in the session view to export the recording into a zip archive:

![image](https://user-images.githubusercontent.com/19209696/218251135-05760ce1-f641-4f09-81fe-2d01e01b5b8b.png)

You can attach the session recording zip archive here in the GitHub issue or send it to support@botlab.org

**Comment by focabr** [comment]
In case you still have some doubts about how to export the session maybe this guide can help you.

https://github.com/Viir/bots/blob/main/guide/how-to-report-an-issue-with-a-bot-or-request-a-new-feature.md
