### ISSUE TITLE
bot error 

### ISSUE THREAD

**Issue by Kosuadk** [Viir/bots#70]
Failed building JavaScript on retry: Failed compiling the bot program code: in file src/CompilationInterface/GenerateJsonCoders.elm: Failed to prepare mapping 'jsonEncodeBotState': Failed to parse type annotation: Failed to parse alias 'State' type annotation: Failed to parse alias 'StateIncludingFramework' type annotation: Failed to parse alias 'StateIncludingFramework' type annotation: Failed to parse annotation of field 'botState': Failed to parse alias 'BotAndLastEventState' type annotation: Failed to parse annotation of field 'lastEvent': Failed to parse annotation of field 'eventResult': Failed to parse constructor 'ContinueSession': Failed to parse argument: Failed to parse alias 'ContinueSessionStructure' type annotation: Failed to parse annotation of field 'screenshotRegionsToRead': FunctionTypeAnnotation not implemented

**Comment by Viir** [comment]
You will see this error with some of the EVE Online bots from last year.
There are new bots for EVE Online now which don't have this problem.

For ratting, switch to bot 45402edb6d from https://github.com/Viir/bots/tree/9fa477cd30c488cd5edee57526a09ce1bde88b76/implement/applications/eve-online/eve-online-combat-anomaly-bot
