### ISSUE TITLE
Tooltip reading stuck when containing text with time

### ISSUE THREAD

**Issue by focabr** [Viir/bots#74]
Hi,

Read tooltip for module button, it's getting stuck while reading when tooltip text contains time.

![image](https://user-images.githubusercontent.com/4109361/222727258-36402eb8-aaad-4114-a719-ae3558fcfab7.png)

I sent session-recording-2023-03-03T12-59-09.zip

If you have any question, feel free to contact me.

Best regards

**Comment by Viir** [comment]
> I sent session-recording-2023-03-03T12-59-09.zip

The session recording did not yet arrive here.

You can send the recording to support@botlab.org
Then I will look into it 👍

**Comment by focabr** [comment]
Hello,

I hope everyone is okay.

Sorry, I had sent the wrong file I sent the wrong file.

Now I am sending the correct file. session-recording-2023-03-03T12-59-09.zip

**Comment by Viir** [comment]
> session-recording-2023-03-03T12-59-09.zip

Thank you for sharing your setup 👍 

It has a module with frequently changing text in the module button tooltip.
This is a novel kind of module, which is not yet covered in the training scenarios.

**Comment by Viir** [comment]
I added new examples adapted to the scenario discovered today. You can find them at https://github.com/Viir/bots/commit/076b7feb2a9629d1925165c741d8bdca95ab2045

The new examples from the link above derive variants from the tooltips where the times are replaced with a constant to get a representation that is fit for the equality comparison between the current tooltip and the previous tooltip.

**Comment by focabr** [comment]
Viir, 

I did the tests here, it worked perfectly.

thank you very much!
